# Generated by Django 5.0.7 on 2024-12-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timeofreq',
        ),
    ]
