# Generated by Django 5.0.7 on 2024-12-15 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_schedule_timeofreq'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timeofreq',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
